#!/bin/bash
#pingimine IP_range 172.23.13.20-172.23.13.50
echo "IP vahemiku algus:"
read algus;
echo "IP vahemiku lopp:"
read lopp;

for (( nr=$algus ; nr<=$lopp ; nr++ ))
do
	ip="172.23.13.$nr"
	ping -c 1 $ip > /dev/null
	if [ $? -eq 0 ]; then
		echo "$ip - OK"
	else
		echo "$ip - not ok"
	fi
done
