#!/bin/bash
#
# kolmnur paremalt vasakule
#
for((r=1; r<6; r++))
do
	# trükime reanumbri ilma reavahetuseta
	echo -n "$r "
	for((v=1; v<$((6-$r+1)); v++))
	do
		# tärnid
		echo -n  "* "
	done
	# kui rida loppeb - reavahetus
	echo
done
