#!/bin/bash
#
# muutujate kasutamise näide
#
# defineerime muutuja ja omistame väärtus
# väärtus saadaks whoami käsust
kasutaja=`whoami`
# väljastan muutuja väärtus koos seletusega
echo "Tere, $kasutaja!"
# loome ja väljastame kell
kell=`date +'%H:%M'`
echo "Kell on $kell"

