#!/bin/bash
# teretab kuidas on aeg pantud
#
echo -e "sisesta aja vaartus: \c"
read aeg
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "tere hommikust!"
elif [ $aeg -ge 12 -a $aeg -lt 16 ]; then
	echo "tere paevast!"
elif [ $aeg -ge 16 -a $aeg -lt 20 ]; then
	echo "tere ohtust!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "head ood!"
else
	echo "vale sisend"
fi

